config/routes.rb
Groups::Application.routes.draw do

  devise_for :users

  root :to => "home#index"

  resources :users, :groups
  
  resources :membership_invitations, :membership_requests do
    member do
      get 'confirm'
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, :through => :memberships
  has_many :membership_invitations
  has_many :membership_requests

  def member?(user)
    users.include?(user)
  end

  def create_group(params,user_id)
    group = Group.create(params)
    group.add_user_to_group(user_id,true)
  end

  def get_groups_user_is_admin(user_id)
    user = User.find(user_id)
    memberships = user.memberships.where(:admin => true)
    groups = memberships.collect {|m| m.group}
    return groups
  end

  def add_user_to_group(user_id,is_admin)
     self.memberships.create(:user_id => user_id, :admin => is_admin) 
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/membership_invitation.rb
class MembershipInvitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  def invite(admin_id,params) 
    @user = User.find(params[:user_id])
    params[:admin_id] = admin_id
    @user.membership_invitations.create(params)
  end

  def confirm(user_id)
    if self.user_id == user_id
       user = User.find(user_id)
       group = Group.find(self.group_id)
       group.add_user_to_group(user_id,false) if not group.member?(user)
    end
  end

  def get_user_invitations(user_id)
    user = User.find(user_id)
    allinv = MembershipInvitation.where(:user_id => user_id)
    allinv.delete_if { |i| Group.find(i.group_id).member?(user)}
  end
end

app/models/membership_request.rb
class MembershipRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  def request(user_id,params)
    @user = User.find(user_id)
    @group = Group.find(params[:group_id])
    @user.membership_requests.create(params) if not @group.member?(@user)
  end

  def confirm(admin_id)
    group = Group.find(self.group_id)
    group.add_user_to_group(self.user_id,false) if not group.member?(user_id)
    self.accepting_admin_id = admin_id
    self.accepted = true
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation

  has_many :memberships
  has_many :groups, :through => :memberships
  has_many :invitations
  has_many :requests, :through => :groups
  has_many :membership_invitations
  has_many :membership_requests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create]

  def show
    @group = Group.find(params[:id])
    @request = User.find(current_user.id).membership_requests.new
  end

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new.create_group(params[:group],current_user.id)
    redirect_to groups_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @groups = Group.all    
    if user_signed_in?
      @invitations = MembershipInvitation.new.get_user_invitations(current_user.id)
    end
 end
end

app/controllers/membership_invitations_controller.rb
class MembershipInvitationsController < ApplicationController
  before_filter :authenticate_user!

  def create
    
    MembershipInvitation.new.invite(current_user.id, params[:membership_invitation])
    redirect_to :back
  end
  
  def confirm
    invitation = MembershipInvitation.find(params[:id])
    invitation.confirm(current_user.id)
    redirect_to :back
  end
end

app/controllers/membership_requests_controller.rb
class MembershipRequestsController < ApplicationController
  before_filter :authenticate_user!

  def create
    MembershipRequest.new.request(current_user.id,params[:membership_request])
    redirect_to :back
  end

  def confirm
    request = MembershipRequest.find(params[:id])
    request.confirm(current_user.id)
    redirect_to :back    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @groups = Group.new.get_groups_user_is_admin(current_user.id) if user_signed_in?
    @invitation = MembershipInvitation.new
    @invitations = MembershipInvitation.where(:user_id => @user.id)


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/index.html.haml
- @groups.each do |g|
  %p= link_to g.name, g

app/views/groups/new.html.haml
- form_for @group do |f|
  %p= f.label :name, "Nazwa"
  %p= f.text_field :name
  %p= f.label :description, "Opis"
  %p= f.text_area :description
  %p= f.submit "Dodaj"

app/views/groups/show.html.haml
%h1= @group.name
- if not @group.member?(current_user)
  - form_for @request do |f|
    %p= hidden_field(:membership_request, :group_id, {:value => @group.id})
    %p= f.submit "Dołącz"
Użytkownicy:
- @group.memberships.each do |m|
  %p= (link_to m.user.email, m.user) + ' ' +(m.admin ? 'Admin' : 'user')
- if not @group.memberships.where(:user_id => current_user.id, :admin => true).empty?
  %hr
  - @group.membership_requests.each do |r|
    %p= link_to "Potwierdź", confirm_membership_request_path(:id => r.id)

app/views/home/index.html.haml
%p= link_to "Dodaj Grupę", new_group_path
%p Zaproszenia:
- if user_signed_in?
  %hr
  - @invitations.each do |i|
    %p= i.group.name 
    = link_to "Potwierdź", confirm_membership_invitation_path(:id => i.id)

%hr
%p Grupy:
- @groups.each do |g|
  %p= link_to g.name, g

%p Użytkownicy:
- @users.each do |u|
  %p= link_to u.email, u

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Groups</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="user_nav">
<%= link_to "Home" ,root_path%>
<% if user_signed_in? %>
<%= link_to current_user.email %>
<%= link_to "Wyloguj", destroy_user_session_path %>
<% else %>
<%= link_to "Zaloguj się", new_user_session_path%>
<% end %>
</div>
<hr>
<p class="notice"><%= notice %> </p>
<p class="alert"><%= alert %> </p>
<%= yield %>

</body>
</html>

app/views/users/show.html.haml
%h1= @user.email
- if @groups != nil
  - form_for @invitation do |f|
    %p= hidden_field(:membership_invitation,:user_id,{:value => @user.id})
    %p= f.select(:group_id, @groups.collect {|g| [g.name,g.id]})
    %p= f.submit "Zaproś"

- if user_signed_in?
  - if @user.id == current_user.id
    %hr
    - @invitations.each do |i|
      %p= i.group.name 
      = link_to "Potwierdź", confirm_membership_invitation_path(:id => i.id)